name: Build Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Set environment variables
        run: |
          echo "ARTIFACT_NAME=eCall-${{ runner.os }}-${{ runner.arch }}" >> "$GITHUB_ENV"
          echo "CMAKE_BUILD_DIR=${{ runner.temp }}/bin" >> "$GITHUB_ENV"
          echo "CMAKE_INSTALL_DIR=${{ runner.temp }}/eCall-${{ runner.os }}-${{ runner.arch }}" >> "$GITHUB_ENV"
          echo "CMAKE_PREFIX_PATH=$Qt6_DIR" >> $GITHUB_ENV
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.3'
          modules: 'qtserialport'
      - name: Install dependencies
        run: |
          sudo apt --yes install libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev libudev-dev uuid-dev linuxdeployqt
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_BUILD_PREFIX="${CMAKE_INSTALL_DIR}" -B "${CMAKE_BUILD_DIR}" .
          cmake --build "${CMAKE_BUILD_DIR}" --parallel "$(nproc)"
          cmake --install "${CMAKE_BUILD_DIR}"
      - name: Run linuxdeployqt
        run: |
          cd "${CMAKE_INSTALL_DIR}/bin"
          linuxdeployqt ./app -verbose=2 -bundle-non-qt-libs
          cd -
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./bin
